# A simple action usage
name: Build Kernel
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Build Kernel
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/gfdvd3/mt6797/tree/cm-14.1
          kernel-dir: msm-4.19
          kernel-branch: cm-14.1
          config: aeon6797_6m_n_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          android-version: 7.1
          aosp-clang-version: r383902
          disable-lto: true
          anykernel3: true
